In [33]:
import numpy as np 
import h5py as h5 
import pickle
matrix = np.arange(100*32*32*32).reshape((100,32,32,32))
targetval = np.arange(100)
# print(matrix)
with h5.File("/tmp/mytestfile.h5", "w") as file1:   
  print(matrix.shape)
  dset = file1.create_dataset("train_x", matrix.shape, dtype='i4', data=matrix, compression="gzip")
  targetvals = file1.create_dataset("train_y", matrix.shape[0], dtype='i4', data=targetval, compression="gzip")

with open("/tmp/mytestfile.pkl", "bw") as file1: 
  pickle.dump(matrix, file1)

  
  
# HDF5 is 187 times smaller than pickle 


(100, 32, 32, 32)


In [34]:
with h5.File("/tmp/mytestfile.h5","r") as file1: 
  print(file1.keys())
  print(file1["train_x"])
  x = list(file1["train_x"])
  print(np.array(x))

<KeysViewHDF5 ['train_x', 'train_y']>
<HDF5 dataset "train_x": shape (100, 32, 32, 32), type "<i4">
[[[[      0       1       2 ...      29      30      31]
   [     32      33      34 ...      61      62      63]
   [     64      65      66 ...      93      94      95]
   ...
   [    928     929     930 ...     957     958     959]
   [    960     961     962 ...     989     990     991]
   [    992     993     994 ...    1021    1022    1023]]

  [[   1024    1025    1026 ...    1053    1054    1055]
   [   1056    1057    1058 ...    1085    1086    1087]
   [   1088    1089    1090 ...    1117    1118    1119]
   ...
   [   1952    1953    1954 ...    1981    1982    1983]
   [   1984    1985    1986 ...    2013    2014    2015]
   [   2016    2017    2018 ...    2045    2046    2047]]

  [[   2048    2049    2050 ...    2077    2078    2079]
   [   2080    2081    2082 ...    2109    2110    2111]
   [   2112    2113    2114 ...    2141    2142    2143]
   ...
   [   2976    2977 

In [14]:
with open("/tmp/mytestfile.pkl","br") as file1: 
  x = pickle.load(file1)
  print(x)

[[[    0     1     2 ...    29    30    31]
  [   32    33    34 ...    61    62    63]
  [   64    65    66 ...    93    94    95]
  ...
  [  928   929   930 ...   957   958   959]
  [  960   961   962 ...   989   990   991]
  [  992   993   994 ...  1021  1022  1023]]

 [[ 1024  1025  1026 ...  1053  1054  1055]
  [ 1056  1057  1058 ...  1085  1086  1087]
  [ 1088  1089  1090 ...  1117  1118  1119]
  ...
  [ 1952  1953  1954 ...  1981  1982  1983]
  [ 1984  1985  1986 ...  2013  2014  2015]
  [ 2016  2017  2018 ...  2045  2046  2047]]

 [[ 2048  2049  2050 ...  2077  2078  2079]
  [ 2080  2081  2082 ...  2109  2110  2111]
  [ 2112  2113  2114 ...  2141  2142  2143]
  ...
  [ 2976  2977  2978 ...  3005  3006  3007]
  [ 3008  3009  3010 ...  3037  3038  3039]
  [ 3040  3041  3042 ...  3069  3070  3071]]

 ...

 [[29696 29697 29698 ... 29725 29726 29727]
  [29728 29729 29730 ... 29757 29758 29759]
  [29760 29761 29762 ... 29789 29790 29791]
  ...
  [30624 30625 30626 ... 30653 30654 306