In [44]:
import numpy as np 
import scipy 
from scipy.ndimage import gaussian_filter
import matplotlib.pyplot as plt 
%matplotlib


a = np.zeros(100).reshape((10,10))


a[(5,5)] = 10
a[(1,1)] = 3
a[(3,6)] = 3

im1 = plt.imshow(a)
b = gaussian_filter(a, sigma=1)
im2 = plt.imshow(b)

cax = plt.axes([0.85, 0.1, 0.075, 0.8])
plt.colorbar(cax=cax)

print(np.sum(b))

Using matplotlib backend: Qt5Agg
16.0


In [25]:
import numpy as np 
import scipy 
from scipy.ndimage import gaussian_filter
import matplotlib.pyplot as plt 

from matplotlib import cm

%matplotlib

with open("./test.pickle", "rb") as file1:
    testdic = pickle.load(file1)
    print(testdic)

fig = plt.figure()
ax = fig.add_subplot(projection='3d')

a = np.arange(30).reshape((10,3))
print(a.shape)
print(len(a))
print(a)

colors= np.arange(0,1,0.1)
thecmap = cm.get_cmap("GnBu")
print(thecmap(0.1))
plt.ion()

for [i, c] in zip(a, colors):
    print(f"i is {i}, c is {c}")
    tmpc = thecmap(c)
    print(tmpc)
    
#     ax.scatter(*i, color=tmpc)


Using matplotlib backend: Qt5Agg


NameError: name 'pickle' is not defined

In [10]:
import numpy as np 
a = np.arange(30).reshape((10,3))
print(a)
for [i, j] in zip(a, range(0,1,1)):
    print(i,j)
    ax.scatter(*i, color=thecmap(j))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]]
[0 1 2] 0


In [14]:
[i for i in np.arange(0,1, 0.1)]

[0.0,
 0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6000000000000001,
 0.7000000000000001,
 0.8,
 0.9]

In [21]:
x={"Protein":":1-221", "Ligand":":LIG", "Solvent":":T3P,CL-,K+"}
for (i, j) in x:
    print(i,j)
    

ValueError: too many values to unpack (expected 2)