In [55]:
import pytraj as pt 

top = "/home/yzhang/zhang/MyTrajs/BFL-1/batch3/C414CsDJQucZ_job_001_END.pdb"; 
traj = "/home/yzhang/zhang/MyTrajs/BFL-1/batch3/C414CsDJQucZ_job_001_traj.nc";
traj = pt.load(traj, top=top, mask=":1-151,:LIG", stride=15)
traj

pytraj.Trajectory, 67 frames: 
Size: 0.003697 (GB)
<Topology: 2469 atoms, 152 residues, 3 mols, PBC with box type = cubic>
           

In [64]:
import numpy as np 

def genslice(traj, center, cube_length): 
  center = np.array(center)
  upperbound = np.array(center) + cube_length/2; 
  lowerbound = np.array(center) - cube_length/2; 
  ret_arr = []
  idx_arr = []
  for xyz in traj.xyz: 
    ubstate = np.array([np.prod(i) for i in xyz < upperbound])
    lbstate = np.array([np.prod(i) for i in xyz > lowerbound])
    state = [bool(i) for i in ubstate*lbstate]
    ret_arr.append(xyz[state])
    idx_arr.append(state)
  return ret_arr, idx_arr

theret, idxs = genslice(traj, [30,32,14], 6)
print(theret[1])

[[32.81624222 31.32039261 15.94249916]
 [30.60195541 29.59212685 15.12362766]
 [31.43644142 30.26342964 15.68272495]
 ...
 [31.04022217 33.51049042 13.67857742]
 [29.76158333 33.99271393 16.41277695]
 [31.26522636 33.02267456 15.95958805]]


In [60]:
print(np.mean(traj.xyz[0][traj.top.select(":LIG")], axis=0))

[30.68020296 32.8807106  14.97895408]


In [14]:
print(traj.xyz[0])
x = traj.xyz[0] < [40,40,20]

print("shape 1", traj.xyz[0].shape)
print("shape 2", x.shape)
print(x)

[[46.37051773 34.39131927 29.53075981]
 [45.66053772 35.65132523 29.4507122 ]
 [45.3305397  36.17137909 30.79069328]
 ...
 [31.42054939 31.98102188 14.00077534]
 [29.52057266 33.81111145 15.68070126]
 [30.80055046 32.71110916 16.19074631]]
shape 1 (21396, 3)
shape 2 (21396, 3)
[[False  True False]
 [False  True False]
 [False  True False]
 ...
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [17]:
np.prod([False,True,False])

0